### ISSUE TITLE
运行hexo-admin start后出现如下问题

### ISSUE THREAD

**Issue by bit-cook** [geekwen/hexo-local-admin#4]
系统是centos6.5
```
/usr/lib/node_modules/hexo-local-admin/module/config-init.js:9
    configPath = PATH.join(OS.homedir(), '.hexo-local-admin-config.json');
                              ^
TypeError: Object #<Object> has no method 'homedir'
    at Object.<anonymous> (/usr/lib/node_modules/hexo-local-admin/module/config-init.js:9:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/hexo-local-admin/bin/hexo-admin.js:8:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by geekwen** [comment]
请问node是什么版本？错误提示是说：OS.homedir 这个方法不存在。OS模块是node内置的模块。

**Comment by bit-cook** [comment]
是安装的是官网最新的稳定版，v7.6.0

**Comment by geekwen** [comment]
我查了一下， 7.6.0的文档里面是有这个方法的啊：https://nodejs.org/dist/v7.6.0/docs/api/os.html#os_os_homedir
麻烦你再确定一下运行环境的版本。

如果确定是 7.6.0 的话，你新建一个 test.js 文档，内容是：
```
var OS = require('os');
console.log(OS.homedir());
```
然后在终端用执行：
```
node test.js
```
看是否会报同样的错误。如果依然报错，那么应该是你 Node 安装有问题。
如果是正确的话，那我也不是很清楚了😂，我找到了这篇issue，到时候我改改：https://github.com/Daplie/greenlock-express/issues/41

**Comment by geekwen** [comment]
另外可以参考下这个：http://stackoverflow.com/questions/38147100/requireos-homedir-error-on-linux

**Comment by bit-cook** [comment]
谢谢
