### ISSUE TITLE
throw error;

### ISSUE THREAD

**Issue by Parkmimi** [geekwen/hexo-local-admin#6]
我之前配置过一次  可能是配置错了 然后现在我再用hexo-admin指令时会抛出如下：
```

C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo-local-admin\module\config-init.js:58
        throw error;
        ^

Error: ENOENT: no such file or directory, access 'C:\Users\Administrator\Documents\blog\your-hexo-path'
    at Object.fs.accessSync (fs.js:301:11)
    at isPathReady (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo-local-admin\module\config-init.js:50:12)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hexo-local-admin\module\config-init.js:28:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by geekwen** [comment]
```
Usage: hexo-admin [options] [command]
Commands:
  start   Start hexo local admin server
Options:
    -h, --help                     output usage information
    -V, --version                  output the version number
    -r, --root-path [root_path]    view/set hexo root path
    -t, --theme-name [theme_name]  view/set hexo theme name
```
看看是否设置了 root-path 和 theme-name

**Comment by ghost** [comment]
之前有设置过 现在无论执行什么命令都会出现如上报错

**Comment by ghost** [comment]
解决了 删除系统文档目录下`.hexo-local-admin-config.json`文件重新设置root path即可。
